---
abstract: 'provide some helper functions for I18N'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-I18NUtils
requires:
  CLDR::Number: '0.09'
  Mojolicious: '4.71'
  Time::Piece: '0'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-I18NUtils/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-I18NUtils
  repository: http://github.com/reneeb/Mojolicious-Plugin-I18NUtils.git
version: '0.13'
